#!/bin/bash

# Script to set up the test target for AskClaude
# This provides instructions for adding tests to the Xcode project

echo "========================================="
echo "AskClaude Test Setup"
echo "========================================="
echo ""
echo "Test files have been created in AskClaudeTests/"
echo ""
echo "To add the test target to your Xcode project:"
echo ""
echo "1. Open AskClaude.xcodeproj in Xcode"
echo "2. Go to File > New > Target..."
echo "3. Select 'Unit Testing Bundle' under macOS"
echo "4. Click Next"
echo "5. Product Name: AskClaudeTests"
echo "6. Team: (leave as default)"
echo "7. Click Finish"
echo "8. When prompted, click 'Activate' to activate the scheme"
echo "9. Delete the auto-generated AskClaudeTests.swift file"
echo "10. Right-click on AskClaudeTests group in project navigator"
echo "11. Select 'Add Files to AskClaude...'"
echo "12. Navigate to and select the AskClaudeTests folder"
echo "13. Make sure 'Add to targets: AskClaudeTests' is checked"
echo "14. Click 'Add'"
echo ""
echo "To run the tests:"
echo "  - In Xcode: Cmd+U"
echo "  - Command line: xcodebuild test -scheme AskClaude -destination 'platform=macOS'"
echo ""
echo "========================================="
echo "Test files created:"
echo "  - ClaudeOutputParserTests.swift (21 tests)"
echo "========================================="
